development:
  base_url: "http://localhost:3000"
  companion_app_base_url: "http://localhost:3001"

production:
  base_url: <%= ENV["APP_BASE_URL"] %>
  companion_app_base_url: <%= ENV["COMPANION_APP_BASE_URL"] %>
