development:
  core_app_domain: "localhost:3000"
  companion_app_domain: "localhost:3001"

production:
  core_app_domain: <%= ENV["CORE_APP_DOMAIN"] %>
  companion_app_domain: <%= ENV["COMPANION_APP_DOMAIN"] %>
