development:
  core_app_url: "http://localhost:3000"
  companion_app_url: "http://localhost:3001"

production:
  core_app_url: <%= ENV["CORE_APP_DOMAIN"] %>
  companion_app_url: <%= ENV["COMPANION_APP_DOMAIN"] %>
